// HARDCODED Supabase config - NEW PROJECT
export const SUPABASE_URL = "https://gdkruvsnqogdnehlwmyg.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka3J1dnNucW9nZG5laGx3bXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMjY5NTAsImV4cCI6MjA4ODkwMjk1MH0.7wDy5nJ_LCazG2X-r_FCd6fgTeGjXg2ZIsw0SB2Nu8c"
export const SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka3J1dnNucW9nZG5laGx3bXlnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzMyNjk1MCwiZXhwIjoyMDg4OTAyOTUwfQ.zlrn924yvCDoWQ_jT1xNOnAorVLhcwx302DsOHZaqVA"
